apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: accountsearch
  name: accountsearch
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accountsearch
  type: LoadBalancer
status:
  loadBalancer: {}
