steps:

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-k', './staging/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cost-optimized-cluster-1'

options:
  machineType: 'N1_HIGHCPU_8'
timeout: 720s
