steps:

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-k', './staging/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=account-search-cb'

options:
  machineType: 'N1_HIGHCPU_8'
timeout: 720s
